image:
  file: .gitpod/Dockerfile
tasks:
- prebuild: cargo build --release && cargo build --target x86_64-unknown-linux-musl --release
  command: cargo watch -x check
vscode:
  extensions:
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==